version: "3.9"
services:
  mongo:
    image: mongo:5.0.3-focal
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "123123"
      MONGO_INITDB_DATABASE: "item"