// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/tuanden0/learn_ent/internal/userapis/user/v1/ent/schema"
	"github.com/tuanden0/learn_ent/internal/userapis/user/v1/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[3].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(uint32)
}
